name: DNMTools builds on Ubuntu

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install dependencies
      run: sudo apt-get install -y libhts-dev libgsl-dev samtools
    - name: Generate configure script
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make with g++
      run: make CXX="g++"
    - name: cleanup after g++
      run: make clean
    - name: install clang dependencies
      run: sudo apt-get install -y libomp-dev
    - name: make with clang++
      run: make CXX="clang++" CXXFLAGS="-fopenmp=libomp"
    - name: cleanup after clang++
      run: make clean
